name: tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths: [ "src/**", "test/**", "project.clj" ]
  pull_request:
    branches: [ main ]
    paths: [ "src/**", "test/**", "project.clj" ]

jobs:
  lein-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: lein test